image: dettmering/hugo-build:0.53

variables:
    url: https://netsplit.uk/

before_script:
    - apk update
    - apk upgrade
    - apk add yarn

stages:
    - generate
    - deploy

generate:
    stage: generate
    script:
        - cd themes/netsplit
        - yarn install
        - cd ../..
        - hugo

deploy:
    stage: deploy
    script:
        - cd themes/netsplit
        - yarn install
        - cd ../..
        - hugo
        - ls -la public
