image: dettmering/hugo-build:0.53

variables:
    url: https://netsplit.uk/

before_script:
    - echo "Test\n";

stages:
    - generate
    - deploy

generate:
    stage: generate
    script:
        - hugo

deploy:
    stage: deploy
    script:
        - echo "Test deploy\n"
        - hugo version
        - ls -la
