image: dettmering/hugo-build:0.53

variables:
    url: https://netsplit.uk/

before_script:
    - apk update
    - apk upgrade
    - apk add yarn
    - apk add openssh-client

stages:
    - generate
    - deploy

generate:
    stage: generate
    script:
        - cd themes/netsplit
        - yarn install
        - cd ../..
        - hugo

deploy:
    stage: deploy
    only:
        refs:
            - master
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - ls ~/.ssh -l
        - cd themes/netsplit
        - yarn install
        - cd ../..
        - hugo
        - scp -r public $OUTPUT_LOCATION
