baseURL = "https://netsplit.uk"
languageCode = "en-gb"
title = "Netsplit Software"
theme = "netsplit"

Paginate = 5

pluralizelisttitles = false

[taxonomies]
author = "authors"
tag    = "tags"

[params]
    gitlab = "https://git.netsplit.uk"
    source = "/mike/netsplit.uk"
    irc    = "https://kiwiirc.com/nextclient/irc.snoonet.org/##netsplit"
    email  = "mike+website@netsplit.org.uk"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    pre = ""
    url = "/about/"
    weight = -110

    [[menu.main]]
    identifier = "projects"
    name = "Open Source"
    pre = ""
    url = "/project/"
    weight = -115
